### ISSUE TITLE
login with vuejs

### ISSUE THREAD

**Issue by juanmp84** [Tony133/Symfony3APIBoilerplateJWTBook#5]
Hi
I need to make a project with symfony but the front with vue js and i choose your api because i always work with symfony and you project is awesome but i have no t idea how to do the login with vue and the token you send in the project have you know of some tutorial of vue js to make this function i ask because a have a restricted internet

thank you

**Comment by Tony133** [comment]
Hello,

Thank you for the compliments happy that my project is useful I hope that the stars increase so, pultroppo vuejs know the framework but never used it, I hope in the future to use it, however try to see these examples: http://jasonwatmore.com/post / 2018/07/06 / vue-vuex-JWT-demonstration authentication-example

https://paweljw.github.io/2017/09/vue.js-front-end-app-part-3-authentication/

the steps with vuejs should be like this:

- after entering a username and password from a form made in vuejs, call the endpoint to login the symfony application that checks the db, if the data is valid, generate the token and from vuejs take the token and you should save it with local storage via js or session storage (and like the php session but managed by js via vuejs) and access your private area or other admin returns an authentication error

Too bad examples of authentication with single page application, there are not many, I hope soon to put them something on github.

A project I had done using a single page application was the crud with angular js (the first version), I did a repo on github.

I hope to be proved helpful

anyway if you need more, write me

Tony133

**Comment by juanmp84** [comment]
Thank you very much for your quick answer I will check thats tutorial and of course you can count with my stars

**Comment by Tony133** [comment]
Nothing thanks to you!

Tony133
